theme: jekyll-theme-slate
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
 - docs/index.md
 - docs/basics.md
 - docs/regions.md
 - docs/points.md
 - docs/radialVelocity.md
 - docs/grids.md
